codefresh/provider_test.go, codefresh/resource_pipeline.go, codefresh/resource_pipeline_test.go, docs/resources/pipeline.md, examples/pipelines.md
This change should allow to set contexts in a pipeline resource. I've compiled a version of the provider from my branch and tested it with a secret context and a config context. The pipeline created loads correctly the contexts.
I've updated the test files, however, I couldn't get the test working locally since I'm getting this error (NOTE: I get the below even from master branch without any change, so this is not related to the changes introduced in this PR):
```
testing_new.go:106: terraform failed: exit status 1
stderr:
Error: Failed to instantiate provider "codefresh" to obtain schema: Unrecognized remote plugin message: 
```
I'm happy to perform further validations and have the test cases validated on my end, but I might need some guidance on how to resolve the above.
Closes #15
=> Support for shared configuration in pipelines

README.md, client/pipeline.go, codefresh/resource_pipeline.go, codefresh/resource_pipeline_test.go, docs/resources/pipeline.md
pipelines trigger are missing option to set the
"pullRequestAllowForkEvents" flag
Much of the "diff" is actually whitespace changes introduced by "gofmt"
=> Add pull_request_allow_fork_events to trigger

codefresh/resource_permission.go, docs/resources/permissions.md
Current list on validation is missing the `debug` action
=> Add support for debug permission

client/user.go
This change addresses the issue where adding a user to many accounts causes a 413 "Request Entity Too Large" response from cfapi.
=> Provide just the account id(s) in the payload sent to the /admin/user/account endpoint - significant reduction in payload size

client/context.go, client/pipeline.go, codefresh/resource_pipeline.go, codefresh/resource_pipeline_test.go, codefresh/resource_project.go, codefresh/resource_step_types.go, go.mod, go.sum
Added business logic to propagate attributes `mode`, `fail_fast`, and `hooks` to the `Spec` section when using the `originalYamlString` setup.
=> fix: propagation of attributes mode, fail_fast, and hooks from originalYamlString

client/pipeline.go, codefresh/resource_pipeline.go, codefresh/resource_pipeline_test.go, docs/resources/pipeline.md
Adding support for the section "Pending approvals" in the pipeline settings.
=> feat: Support Pending Approval options in pipelines

client/user.go
Note that this provider will no longer work in against versions of codefresh pre-1.0.184 release.
In a simple synthetic test of 100 users in across 5 accounts, the terraform refresh went from 2m36.370s in the current provider version to 0m5.214s with this patch.
=> Moved to use the new /api/admin/user/id/<user_ID> endpoint - available in 1.0.184

docs/resources/api-key.md
`user_id` is a required parameter to use this resource; considering the diffs between on-prem & SaaS, I didn't feel the need to complicate the examples anymore by adding data call for user, but that is important. 
It should probably be noted that the majority of the [currently documented resources|https://registry.terraform.io/providers/codefresh-io/codefresh/latest/docs/resources/user] do not play well with self-hosted deployments.  I'm testing getting this resource working with a self-hosted deployment and will update as needed if I'm able to get a working model going.
=> Update arguments for `codefresh_api_key` resource

client/pipeline.go, codefresh/resource_pipeline.go, codefresh/resource_pipeline_test.go, docs/resources/pipeline.md
Include pipeline caching behaviors and notification setting.
Caching behaviors are documented in [git-triggers](https://codefresh.io/docs/docs/integrations/codefresh-api/#git-triggers) and [api documentation](https://g.codefresh.io/api/#operation/pipelines-create)
This is for issue #58
=> Add trigger options

client/pipeline.go, codefresh/resource_pipeline.go
Type should be bool rather than string.
=> Fix type for trigger options

client/pipeline.go, codefresh/resource_pipeline.go, tools.go
Added pack_id to support the different size available
It takes the uuid for now
Improvement would be to transform the"name" like Large, XXL into the uid
But I don't know go so easiest solution to make it work
=> #28: add pack_id to support Saas package size

codefresh.yml
Per https://goreleaser.com/deprecations/?h=darwi#builds-for-darwinarm64 you need version 1.16 or higher to build Darwin/arm64 versions. 
I have updated the version to the latest so we can release version that supports the M1 Macs
=> Update goreleaser version to 1.6.3

client/user.go
The response when a user does not exist is: something like:
{"status":500,"code":"1001","name":"INTERNAL_SERVER_ERROR","message":"could not delete user:<USERNAME>, err: \"User does not exist\"","context":{}} 
It really should be a 404, but to change the api would be a breaking-change. Instead, we should parse the response and return an err only if the RequestAPI returns an error and the response does not contain "User does not exist".
=> Add logic to not return error in DeleteUser when no user is found

client/team.go
Use _id when unmarshalling the API response for team members
Recent versions of the codefresh API do not return `id` for team members, only `_id`. See #93 for more details
Closes #93
=> Use _id when unmarshalling team members API response

GNUmakefile, README.md, client/pipeline.go, codefresh/resource_pipeline.go, docs/developer.md, docs/resources/pipeline.md
Signed-off-by: Laurent <laurent.rochette@codefresh.io>
Added the new field to reserver disk space
Requested by customer
=> CR-16640: Add requiredAvailableStorage

docs/README.md
Path to  the account_token file was incorrect
Broken link
Change accounts_token.md to account_token.md to reflect  the correct filename
=> Change link to account_token

.github/workflows/docs.yaml, GNUmakefile, templates/index.md.tmpl
* Fix docs workflow
(workflow was not working)
=> Fix: docs workflow

client/account.go, codefresh/resource_account.go
* Fix `codefresh_account` refresh for on-prem installations
* On-prem API does not return 'limits' field
=> Fix `codefresh_account` refresh for on-prem installations

client/pipeline.go, codefresh/resource_pipeline.go, docs/resources/pipeline.md
- Add `RequiredAvailableStorage` to the `RuntimeEnvironment` spec
The current provider doesn't support configuration of required available storage for hybrid runtimes.
=> Add RequiredAvailableStorage parameter to RuntimeEnvironment

README.md
Changed:
```
source = "codefresh.io/codefresh"
```
To:
```
source = "codefresh-io/codefresh"
```
Dots are not accepted:
```
│ Error: Invalid provider namespace
│
│   on _providers.tf line 8, in terraform:
│    8:       source = "codefresh.io/codefresh"
│
│ Invalid provider namespace "" in source "codefresh.io/codefresh": dots are not 
│ allowed"
```
=> fix provider source location

client/pipeline.go, codefresh/resource_pipeline.go, codefresh/resource_pipeline_cron_trigger.go, codefresh/resource_pipeline_test.go, docs/resources/pipeline.md, docs/resources/pipeline_cron_trigger.md, templates/resources/pipeline.md.tmpl, templates/resources/pipeline_cron_trigger.md.tmpl
`[codefresh_pipeline]`: add `spec.cron_trigger`
New feature that supersedes [pipeline_cron_trigger](https://registry.terraform.io/providers/codefresh-io/codefresh/latest/docs/resources/pipeline_cron_trigger) added in #90 (the API used by `pipeline_cron_trigger` is limited; additional cron trigger options were recently added to the pipelines API, currently behind a feature flag)
Will be first released as part of `0.6.0-beta-1` (pre-release)
=> Add inline cron triggers to `codefresh_pipeline`

codefresh.yml
* Concurrent provider acceptance tests against different terraform versions
* Install Terraform beforehand, do not delegate Terraform SDK v2 to do download and install Terraform
* There is an issue caused when parallel Terraform Provider acceptance tests install Terraform at the same time. Explained fairly well in https://github.com/hashicorp/terraform-provider-kubernetes/pull/2256
* Better testing by using different versions of the Terraform binary (3 latest stable minor versions — their latest stable patch version resolved by [terraform-switcher](https://github.com/warrensbox/terraform-switcher) aka `tfswitch`)
* Will probably need to test against OpenTofu in the future
=> ci: Concurrent Provider Acceptance Tests against Different Terraform Versions 

codefresh/cfclient/pipeline.go, codefresh/resource_pipeline.go, codefresh/resource_pipeline_test.go, docs/resources/pipeline.md
Add possibility to disable restart From failed step in pipeline resource.
This property was absent from the terraform provider, causing the default "true" value to always be applied and would reset manual changes on apply
=> Feat: Add permit restart from failed steps to pipeline resource

codefresh.yml
Update supported terraform versions in CI pipeline
=> Feat: Update supported terraform versions - Minimal version 1.3.0 and Maximum version 1.7.0

codefresh/cfclient/pipeline.go, codefresh/cfclient/project.go, codefresh/cfclient/utils.go, codefresh/internal/datautil/strings.go, codefresh/resource_pipeline.go, codefresh/resource_pipeline_test.go, codefresh/resource_project.go, codefresh/resource_project_test.go, docs/resources/pipeline.md, docs/resources/project.md
Support for encrypted variables - closes #97
=> Feat: Support encrypted variables in project and pipeline (including triggers)

codefresh/cfclient/user.go, codefresh/resource_user.go, docs/resources/user.md
to unset password at least version `21.253.9` of cf-api is required
=> Feat: Support local password for users

codefresh/cfclient/user.go
=> Fix: User data source times out on getting all users - add pagination

codefresh/cfclient/user.go, codefresh/data_account.go, codefresh/data_account_gitops_settings.go, codefresh/data_idps.go, codefresh/data_user.go, codefresh/data_users.go, codefresh/resource_account.go, codefresh/resource_account_admins.go, codefresh/resource_account_gitops_settings.go, codefresh/resource_api_key.go, codefresh/resource_idp.go, codefresh/resource_user.go, docs/data-sources/account.md, docs/data-sources/idps.md, docs/data-sources/user.md, docs/data-sources/users.md, docs/resources/account.md, docs/resources/account_admins.md, docs/resources/account_gitops_settings.md, docs/resources/api_key.md, docs/resources/idp.md, docs/resources/user.md, templates/resources/account_gitops_settings.md.tmpl
=> patch - update docs: specify which resources require admin token

codefresh/resource_abac_rules.go, codefresh/resource_abac_rules_test.go, docs/resources/abac_rules.md
=> feat: add abac rules for products, environments, and promotion flows

codefresh/cfclient/client.go, codefresh/cfclient/context.go, codefresh/cfclient/current_account.go, codefresh/context/storage.go, codefresh/data_context.go, codefresh/provider.go, codefresh/resource_context.go, codefresh/resource_context_test.go, docs/resources/context.md, templates/resources/context.md.tmpl
=> fix: codefresh_context disable decrypt when forbidDecrypt feature flag is set

codefresh/cfclient/pipeline.go, codefresh/data_current_account_user.go, codefresh/resource_pipeline.go, codefresh/resource_pipeline_test.go, docs/resources/pipeline.md
This fixes `permit_restart_from_failed_steps` behavior in `pipeline` resource.
Before this fix, setting `permit_restart_from_failed_steps = false` or omitting this key resulted in “Permit restart from failed step: Use account settings” for both cases.
New syntax/behavior is:
`permit_restart_from_failed_steps = [true|false]` with the default value `true` (“Permit”).
If `false`, the policy is set to “Forbid”.
New flag is added: `permit_restart_from_failed_steps_use_account_settings = [false|true]` with the default value `false` (“do not use account settings”).
If `true`, `permit_restart_from_failed_steps` will be ignored and pipeline policy will be set to “Use account settings”.
> [!WARNING]
> BREAKING CHANGES!
> * Previously, `permit_restart_from_failed_steps = false` resulted in “Permit …
=> fix(resource/pipeline): fix `permit_restart_from_failed_steps = false`

codefresh/data_current_account_user.go, codefresh/data_idps.go, codefresh/internal/datautil/yaml.go, codefresh/resource_account_user_association.go, codefresh/resource_permission.go, codefresh/resource_permission_test.go, codefresh/resource_step_types.go, docs/resources/permission.md
=> feat: add runtime-environment resource support to codefresh_permission resource

codefresh/cfclient/api_key.go, codefresh/cfclient/user.go, codefresh/resource_account_user_association_test.go, codefresh/resource_user.go
=> fix - remove unnecessary unmarshalling in codefresh_user activation
